import { Component, OnInit } from '@angular/core';
import { EventData, Slider } from '@nativescript/core';

declare var java : any;

@Component({
  moduleId: module.id,
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {

  myNumber : number = 0;

  countries: { name: string, imageSrc: string }[] = [
    { name: "Australia", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/au.png" },
    { name: "Belgium", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/be.png" },
    { name: "Bulgaria", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/bg.png" },
    { name: "Canada", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/ca.png" },
    { name: "Switzerland", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/ch.png" },
    { name: "China", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/cn.png" },
    { name: "Czech Republic", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/cz.png" },
    { name: "Germany", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/de.png" },
    { name: "Spain", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/es.png" },
    { name: "Ethiopia", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/et.png" },
    { name: "Croatia", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/hr.png" },
    { name: "Hungary", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/hu.png" },
    { name: "Italy", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/it.png" },
    { name: "Jamaica", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/jm.png" },
    { name: "Romania", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/ro.png" },
    { name: "Russia", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/ru.png" },
    { name: "United States", imageSrc: "https://play.nativescript.org/dist/assets/img/flags/us.png" },
  ];

  minDate: Date = new Date(1975, 0, 29);
  maxDate: Date = new Date(2045, 4, 12);

  onDatePickerLoaded(args : any) {
      // const datePicker = args.object as DatePicker;
  }

  onDateChanged(args : any) {
      console.log("Date New value: " + args.value);
      console.log("Date value: " + args.oldValue);
  }

  onDayChanged(args : any) {
      console.log("Day New value: " + args.value);
      console.log("Day Old value: " + args.oldValue);
  }

  onMonthChanged(args : any) {
      console.log("Month New value: " + args.value);
      console.log("Month Old value: " + args.oldValue);
  }

  onYearChanged(args : any) {
      console.log("Year New value: " + args.value);
      console.log("Year Old value: " + args.oldValue);
  }

  onSliderValueChange(args : any) {
    let slider = <Slider>args.object;
    console.log(`Slider new value ${args.value}`);
  }
 
  constructor() { }

  ngOnInit(): void {
    
  }

  onItemTap(args : EventData) {
    console.log(args);
  }

  onTap(args : EventData) {
    this.myNumber++;
    // let date = java.time.LocalDate.now();
    //this.myNumber = java.lang.Math.min(3, 4);
    //let timestampLocal = new java.Timestamp(java.System.currentTimeMillis());
    //this.timestamp = timestampLocal;
    //this.myNumber = timestamp;
  }

}
